### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zc.monitor#3]
The first step was made in #1. But #2 relieved that the tests and even the code of this package need `zc.ngi` which is not yet ported to Python 3 (see zopefoundation/zc.ngi#2). To run  `zc.monitor` on Python 3 we

* either need to port `zc.ngi` to Python 3
* or use another library for the network access (@jimfulton suggested to [switch to `asyncio`](https://github.com/zopefoundation/zc.ngi/pull/1#issuecomment-326263758)).

**Comment by icemac** [comment]
I have no personal interest in this package I submitted this issue while working on a release for #1.

**Comment by jugmac00** [comment]
@stevepiercy Are you still interested in this package? If not I'd suggest to archive it, as there is no working Python 3 version.

**Comment by stevepiercy** [comment]
I am not interested because I don't care about running machines with Python 2.

However there might be some folks who still use Python 2 with https://github.com/plone/ansible-playbook.

Nonetheless, I think it's fine to archive this repo. Can any member of the GitHub team `zopefoundation` unarchive if needed?

**Comment by jugmac00** [comment]
@stevepiercy Thank you for the feedback!

Usually @icemac is the one who archives obsolete packages. He then leaves a notice, that - in case somebody needs it anyway - whoever can open an issue over here:
https://github.com/zopefoundation/meta/issues

@icemac Please archive this package and deactivate Travis!
Thank you!

**Comment by icemac** [comment]
Going to archive the package now.
